<?php $this->layout()->setLayout('login'); ?>

<div class="">
	<?php echo $this->render('globals/menu_admin.phtml'); ?>
</div>

<div class="row">
	<div class="twelve columns centered">
		<h2>Categorie</h2>
		<h4 class="subheader">Totale <?php echo count($this->category); ?></h4>

		<?php if ($this->category): ?>
		<table class="twelve">
			<thead>
				<tr>
					<th>Operazione</th>
					<th>Operazione</th>
					<th>Categoria</th>
					<th>Genitore</th>
					<th>Sotto categoria</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->category as $row): ?>
				<tr>
					<td><a class="button" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'category', 'action' => 'edit', 'id' => $row['id'])); ?>">Modifica</a></td>
					<td>
						<a class="alert button" data-reveal-id="deleteModal_<?php echo $row['id']; ?>" href="javascript:void(0)">Cancella</a>
						<div id="deleteModal_<?php echo $row['id']; ?>" class="reveal-modal">
							<h2>Esegui Logout</h2>
							<p class="lead">Sei sicuro di voler eliminare <?php echo $row['name']; ?>?</p>
							<a class="secondary button" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'category', 'action' => 'delete', 'id' => $row['id'])); ?>">SI</a>
							<a class="close-reveal-modal">&#215;</a>
						</div>
					</td>
					<td><?php echo $row['name']; ?></td>
					<td><?php echo $this->alert[$row['parent']]; ?></td>
					<td><?php echo $row['sub_name']; ?></td>
				</tr>
				<?php endforeach ?>
			</tbody>
		</table>
		<?php else: ?>
			<div class="alert-box"><?php echo $this->notfound; ?><a href="" class="close">&times;</a></div>
		<?php endif ?>

	</div>

</div>

<?php echo $this->render('globals/copyright_admin.phtml'); ?>
