 <div class="row">
        <div class="span12">
            <div style="padding:12px;">
            <div class="navbar">
                <div class="navbar-inner">
                    <a class="brand" href="#">My Account</a>
                        <ul class="nav pull-left">
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'avatar'), null, true); ?>"><i class="icon-picture"></i> Immagine di Profilo</a></li>
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'edit'), null, true); ?>"><i class="icon-edit"></i> Modifica Dati</a></li>
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'editpassword'), null, true); ?>"><i class="icon-lock"></i> Modifica Password</a></li>
                            <?php if($this->identity->type == 2): ?>
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page'), null, true); ?>"><i class="icon-globe"></i> Brand Page</a></li>
                        <?php endif ?>
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'favorites'), null, true); ?>"><i class="icon-star"></i> Preferiti</a></li>
                        </ul>
                        <ul class="nav pull-right">
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), null, true); ?>"><i class="icon-off"></i> Logout</a></li>
                        </ul>

                        <a class="btn btn-warning pull-right" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'my'), null, true); ?>"> I Miei Annunci</a>

                </div>
            </div>
            </div>
        </div>
    </div>
