

	<a class="btn btn-warning" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'edit'), null, true); ?>">Modifica Dati</a>
	<a class="btn btn-warning" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'picture'), null, true); ?>">Modifica Logo</a>
	<a class="btn btn-warning" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'gallery'), null, true); ?>">Gallery</a>
	<a class="btn btn-warning" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'subscription'), null, true); ?>">Abbonamento</a>
