<h1>Mini Sito</h1>
<ul>
	<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'edit'), null, true); ?>">Modifica Dati</a></li>
	<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'picture'), null, true); ?>">Modifica Logo</a></li>
	<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'gallery'), null, true); ?>">Gallery</a></li>
	<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'subscription'), null, true); ?>">Abbonamento</a></li>
</ul>
<hr>