<?php echo $this->render('globals/menu_user.phtml'); ?>
<?php echo $this->render('globals/menu_company.phtml'); ?>

<?php echo $this->galleryForm; ?>

<?php if(count($this->gallery) > 0): ?>
    <?php foreach ($this->gallery as $row): ?>
     	<p>
     		<img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=gallery&image=<?php echo $row['image']; ?>&width=100&height=100">
            <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'deletegallery', 'item' => $row['id'])); ?>">Elimina</a>
        </p>
    <?php endforeach ?>
<?php endif; ?>