<?php
echo $this->headTitle(sprintf('%s - Bazoomba Page', $this->user['name_company']));
$locale = new Zend_Locale('it_IT');
?>

<div class="container" style="background-color: #fff; margin-top: 30px; margin-bottom: 20px;  -moz-box-shadow:0 2px 15px #898989;-webkit-box-shadow:0 2px 15px #898989;box-shadow:0 2px 15px #898989;">

    <div class="row">
        <div class="span12">
            <div style="background-color: #f2f2f2; position: relative;">

                <div class="row">
                    <div class="span3">
                        <img style="position: absolute; padding: 5px; background-color: #fff; -moz-box-shadow:0 2px 15px #898989;-webkit-box-shadow:0 2px 15px #898989;box-shadow:0 2px 15px #898989;  top: -10px; left: 15px; z-index: 5;" src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=logo&image=<?php echo $this->logo; ?>&width=250&height=100" alt="<?php echo $this->user['name']; ?>" title="<?php echo $this->user['name']; ?>"/>
                    </div>
                    <div class="span4">
                        <h3><?php echo ucwords($this->user['name_company']); ?></h3>
                    </div>
                    <div class="span5">
                        <div style="margin-top: 20px;">
                        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'links'), null, true); ?>?url=<?php echo $this->page['site']; ?>&location=3" target="_blank"><button class="btn btn-mini"><i class="icon-globe"></i> <?php echo $this->page['site']; ?></button></a>
                        <a href="#"><button class="btn btn-mini"><i class="icon-envelope"></i> <?php echo $this->page['telephone']; ?></button></a>
                        <a href="#"><button class="btn btn-mini"><i class="icon-info-sign"></i> P.Iva <?php echo $this->user['vat']; ?></button></a>
                        </div>
                    </div>
                </div><!--row-->

            </div><!--style-->
        </div><!--span12-->
    </div><!--row-->

    <div class="row">
        <div class="span12">
                <div style="width: 100%; height: 300px;" id="mapsbrand"></div>
        </div>
    </div>


    <div class="row">
        <div class="span6">
            <div style="padding: 12px;">
            <h3>Chi Siamo</h3>
            <p><?php echo nl2br($this->page['description']); ?></p>
            </div>
        </div>

        <div class="span6">
            <div style="padding: 12px;">
            <h3>Gallery</h3>
            <?php if(count($this->gallery) > 0): ?>
                <?php foreach ($this->gallery as $row): ?>

                            <img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=gallery&image=<?php echo $row['image']; ?>&width=100&height=100">

                <?php endforeach ?>
            <?php else: ?>
                            <div class="alert alert-box">Le foto devono ancora essere caricate.</div>
            <?php endif; ?>
            </div>
        </div>

    </div>


    <div class="row">
        <div class="span12">
            <div style="padding: 12px;">
                <h3>Annunci di <?php echo ucwords($this->user['name_company']); ?> (<?php echo count($this->ads); ?>)</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="span12">

            <?php if(count($this->ads) > 0): ?>
            <ul class="thumbnails">
                <?php $cnt = 1; ?>
                <?php foreach ($this->ads as $row): ?>

                <li class="span4" style="background: #fff;">
                        <div class="thumbnail">
                        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>"><img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=480&height=360" alt="<?php echo $row['title']; ?>" title="<?php echo $row['title']; ?>">
                        <div class="caption" style="min-height: 170px;">
                            <h4><a class="hh" rel="tooltip" data-placement="top" title="Tooltip on top" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>"><?php echo $row['title']; ?></a></h4>
                            <p><?php echo $this->truncate($row['description'])->toLength(100); ?></p>
                            <p><a href="#" class="btn btn-warning">€ <?php echo Zend_Locale_Format::toNumber($row['price'], array('precision' => 2, 'locale' => $locale)); ?></a>
                            <button title="Tip Utente <?php echo $this->type_user[$row['type_user']]; ?> - <?php echo $row['category']; ?> - <?php echo $row['province']; ?>" type="button" class="btn"><i class="icon-info-sign"></i></button></p>
                        </div>
                        </div>
                        </li>
                <?php if($cnt % 3 == 0): ?>
                </ul>
                <ul class="thumbnails">
                <? endif; ?>


                    <?php $cnt++; ?>
                    <?php endforeach ?>


            </ul>
            <?php else: ?>
            <div class="alert alert-box">
                <strong><?php echo $this->user['name_company']; ?></strong> non ha ancora caricato annunci.
            </div>
            <?php endif; ?>



            
        </div>
    </div>




</div><!--container-->

<script type="text/javascript">
var vikey = [{ stylers: [{ gamma: 0.52 },{ saturation: 11 } ] }];
var latlang = new google.maps.LatLng(<?php echo $this->page['latitude']; ?>, <?php echo $this->page['longitude']; ?>);
var mapOptions = {
    center: latlang,
    zoom: 9,
    disableDefaultUI: true,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    styles: vikey
};

var map = new google.maps.Map(document.getElementById("mapsbrand"),
mapOptions);
var marker = new google.maps.Marker({ position: latlang,map: map,title: "<?php echo $this->user['name_company']; ?>" });
</script>

