<div id="maps" style="width: 100%; height: 600px;" class="row-fluid visible-desktop">
</div>

<div class="container">

      <!-- Example row of columns -->
      <div class="row">

        <div class="span4">
          <h2 class="muted">Cerchi qualcosa?</h2>
          <p class="lead">Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh. </p>
          <p><a class="btn btn-warning" href="#">Scopri come cercare &raquo;</a></p>
        </div>
        <div class="span4">
          <h2 class="muted">Vuoi vendere qualcosa?</h2>
          <p class="lead">Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh. </p>
          <p><a class="btn btn-warning" href="#">Inizia Vendere subito &raquo;</a></p>
       </div>
        <div class="span4">
          <h2 class="muted">Scopri come funziona</h2>
          <p class="lead">Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper.</p>
          <p><a class="btn btn-warning" href="#">Tutte le riposte che cerchi &raquo;</a></p>
        </div>


      </div>


    </div> <!-- /container -->
