<h1>Ultimi annunci pubblicati...</h1>
<?php if ($this->shop): ?>
	<?php foreach ($this->shop as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>"><?php echo $row['title']; ?></a></li>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'category', 'item' => $row['category']), null, true); ?>"><?php echo $row['name_category']; ?></a> :: <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'region', 'item' => $row['region']), null, true); ?>"><?php echo $row['name_region']; ?></a></li>
		<li><?php echo $this->truncate($row['description']); ?></li>
		<li><?php echo $this->type_ads[$row['type']]; ?>, € <?php echo $row['price']; ?></li>
		<li><?php echo $this->type_user[$row['type_user']]; ?></li>
	</ul>
	<hr>
	<?php endforeach ?>
<?php endif ?>

