<?php $this->layout()->setLayout('login'); ?>

<div class="">
	<?php echo $this->render('globals/menu_admin.phtml'); ?>
</div>

<div class="row">
	<div class="twelve columns">
		<h2>Dashboard</h2>
		<h4 class="subheader">Benvenuto, <?php echo $this->identity->name; ?>...</h4>
	</div>
</div>

<div class="row">
	<div class="twelve columns">
		<form action="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'item')); ?>" method="get" accept-charset="utf-8">
			<div class="row collapse">
				<div class="ten mobile-three columns">
					<input type="text" autocomplete="on" name="q" value="" placeholder="es. Iphone 5s, Mercedes, Divano" />
				</div>
				<div class="two mobile-one columns">
					<input type="submit" class="button expand postfix" value="Cerca" />
				</div>
			</div>
		</form>
	</div>
</div>

<div class="row">
	<div class="six columns">
		<h4 class="subheader">Ultimi annunci pubblicati</h4>
		<table class="twelve">
			<thead>
				<tr>
					<th>Annuncio</th>
					<th>Pubblicazione</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->last_ads as $row): ?>
				<tr>
					<td><a class="has-tip" data-width="250" title="Utente: <?php echo $row['user']; ?>" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'detail', 'id' => $row['id'])); ?>"><?php echo $row['title']; ?></a></td>
					<td><?php echo new Zend_Date($row['registered']); ?></td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>

<div class="six columns">
	<h4 class="subheader">Operazioni in corso</h4>
	<table class="twelve">
		<thead>
			<tr>
				<th>Annuncio</th>
				<th>Revisione</th>
				<th>Stato</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->view_ads as $row): ?>
			<tr>
				<td><a class="has-tip" data-width="250" title="Utente: <?php echo$row['user']; ?>" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'detail', 'id' => $row['id'])); ?>"><?php echo $row['title']; ?></a></td>
				<td><?php echo new Zend_Date($row['modified']); ?></td>
				<td><img src="<?php echo $this->serverUrl(); ?>/admin/images/<?php echo $row['status']; ?>.png"></td>
			</tr>
		<?php endforeach ?>
	</tbody>
</table>
</div>
</div>

<?php echo $this->render('globals/copyright_admin.phtml'); ?>