<?php $this->headTitle('Immagine di profilo - '.$this->identity->name.''); ?>
<div class="container" style="background-color: #f0f0f0; border-radius: 15px; margin-top: 20px;">

    <?php echo $this->render('globals/menu_user.phtml'); ?>

    <div class="row">
        <div class="span12">
            <div style="padding: 12px;">

                <div style="background-color: #fff; padding: 10px; border: 1px solid #ccc; border-radius: 5px; margin-top: -25px;">





                     <div class="row" style="margin-top: 10px; margin-bottom: 10px;">


                         <div class="span3">

                             <?php if($this->avatar > 0): ?>
                                <img class="photoAT" src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=avatar&image=<?php echo $this->avatar ?>&width=480&height=360" />
                             <?php else: ?>
                                <?php echo $this->gravatar($this->identity->email, array('imgSize' => 480)); ?>
                             <?php endif; ?>

                         </div>

                         <div class="span8">
                             <div style="padding: 12px;">

                               <?php echo $this->addAvatar; ?>

                            </div><!--padding-->
                         </div><!--span8-->

                     </div><!-- row-->




                </div><!--style-->
            </div><!--padding-->
        </div><!--12-->
    </div><!--row-->

</div><!--container-->

