<?php $this->headTitle('Modifica Password - '.$this->identity->name.''); ?>
<div class="container" style="background-color: #f0f0f0; border-radius: 15px; margin-top: 20px;">

    <?php echo $this->render('globals/menu_user.phtml'); ?>

    <div class="row">
        <div class="span12">
            <div style="padding: 12px;">

                <div style="background-color: #fff; padding: 10px; border: 1px solid #ccc; border-radius: 5px; margin-top: -25px;">


                    <h1>Modifica la tua password</h1>
                    <?php echo $this->successForm; ?>
                    <?php echo $this->editPassword; ?>





                </div><!--style-->
            </div><!--padding-->
        </div><!--12-->
    </div><!--row-->

</div><!--container-->
