<?php echo $this->headTitle($this->category['name']); ?>

<!-- title / category -->
<h1>Categoria <?php echo $this->category['name']; ?></h1>

<!-- category -->
<?php if ($this->parent): ?>
	<?php foreach ($this->parent as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'subcategory', 'item' => $this->category['id'], 'parent' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['name']); ?>"><?php echo $row['name']; ?></a></li>
	</ul>
	<?php endforeach ?>
<?php endif ?>

<!-- type_ads -->
<h1>Cosa cerchi?</h1>
<?php foreach ($this->type_ads as $key => $value): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'category', 'item' => $this->category['id'], 'ads' => $key), null, true); ?>"><?php echo $value; ?></a></li>
	</ul>
<?php endforeach ?>

<!-- type_user -->
<h1>Come?</h1>
<?php foreach ($this->type_user as $key => $value): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'category', 'item' => $this->category['id'], 'user' => $key), null, true); ?>"><?php echo $value; ?></a></li>
	</ul>
<?php endforeach ?>

<!-- list ads -->
<h1>Lista <?php echo count($this->list); ?></h1>
<?php if ($this->list): ?>
	<?php foreach ($this->list as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>"><?php echo $row['title']; ?></a></li>
		<li><?php echo $this->truncate($row['description']); ?></li>
		<li><?php echo $row['region']; ?>, <?php echo $row['province']; ?></li>
		<li><?php echo $this->type_ads[$row['type']]; ?>, € <?php echo $row['price']; ?></li>
		<li><?php echo $this->type_user[$row['type_user']]; ?></li>
		<li><img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=100&height=100"></li>
	</ul>
	<hr>
	<?php endforeach ?>
<?php else: ?>
	<p><?php echo $this->notfound; ?></p>
<?php endif ?>


<!-- category -->
<h1>Categorie</h1>
<?php if ($this->other): ?>
	<?php foreach ($this->other as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'category', 'item' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['name']); ?>"><?php echo $row['name']; ?></a></li>
	</ul>
	<?php endforeach ?>
<?php endif ?>
