<?php $this->headTitle('Ricerca'); ?>

<div class="container">
    <div class="row">

        <div class="span6">
            <h1>Ricerca</h1>
            <?php echo $this->searchForm; ?>

            <!-- Random List ADS -->
            <?php if ($this->list): ?>
            <?php foreach ($this->list as $row): ?>
                <ul>
                    <li>
                    <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>">
                    <?php echo $row['title']; ?>
                    </a>
                    </li>
                </ul>
                <?php endforeach ?>
            <? endif; ?>


        </div>
        <!--span6-->

        <div class="span6">

            <div class="row">
                <div class="span3">
                    <h1>Italia</h1>
                    <?php if ($this->region): ?>
                    <?php foreach ($this->region as $row): ?>
                        <ul>
                            <li>
                            <a href="
                            <?php echo $this->serverUrl(); ?><?php echo $this->url(
                                    array(
                                            'controller' => 'filter', 
                                            'action' => 'region', 
                                            'item' => $row['id']), null, true
                            ); ?>/<?php echo $this->seourl($row['name']); ?>">
                            <?php echo $row['name']; ?>
                            </a>
                            </li>
                        </ul>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>

                <div class="span3">
                    <h1>Categorie</h1>
                    <?php if ($this->category): ?>
                    <?php foreach ($this->category as $row): ?>
                        <ul>
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(
                                    array(
                                        'controller' => 'filter', 
                                        'action' => 'category', 
                                        'item' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['name']); ?>">
                                        <?php echo $row['name']; ?>
                                        </a>
                                        </li>
                        </ul>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>
            </div>


        </div>
        <!--span6-->

    </div>
    <!--row-->


</div><!--contaner-->

<script src="<?php echo $this->serverUrl(); ?>/site/js/jquery.autocomplete.js"></script>

