<?php
$this->headTitle($this->region['name']);
$locale = new Zend_Locale('it_IT');
?>

<div class="container" style="margin-top: 20px;">

    <!-- Example row of columns -->
      <div class="row">

        <div class="span2">
         <div class="btn-group" style="margin-bottom: 10px;">
                <button class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i> Elettronica <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><a href="#">Console & Videogame</a></li>
                  <li><a href="#">Informatica</a></li>
                  <li><a href="#">Audio/Video</a></li>
                  <li><a href="#">Fotografia</a></li>
                  <li class="divider"></li>
                  <li><a href="#myModal" role="button" data-toggle="modal"><i class="icon-refresh"></i> Cambia Categoria</a></li>
                </ul>
              <button class="btn" style="margin-left: 5px;"><i class="icon-th"></i></button>
              </div><!-- /btn-group -->


          <ul class="nav nav-tabs nav-stacked" style="background: #fff;">
              <li><a href="#"><strong>Annunci Trovati </strong><span class="badge badge-warning"> <?php echo $this->cnt; ?></span></a></li>
              <li><a href="#"><i class="icon-tags"></i> Tags</a></li>
              <li><a href="#"><i class="icon-bookmark"></i> Preferiti</a></li>
              <li><a href="#"><i class="icon-map-marker"></i> Provincia</a></li>
              <li><a href="#"><i class="icon-eye-open"></i> Voce Uno</a></li>
              <li><a href="#"><i class="icon-random"></i> Voce Due</a></li>
            </ul>
        <div class="alert alert-success">
        <strong>Non hai trovato quello che cerhi?</strong>
        <p>Non demordere, scopri il nostro servizio che ti trova subito ciò che ti serve.
        <a href="#">Provalo adesso</a></p>
        </div>

        <div class="alert alert-success">
        <strong>Sei un azienda?</strong>
        <p>Scopri <strong>Brand Page</strong>.<br />
        <a href="#">Scopri adesso</a></p>
        </div>

        </div>
        <div class="span10">
          <div id="maps_canvas" style="width: 100%; height: 617px; margin-bottom: 20px; -moz-box-shadow:0 2px 10px #898989;-webkit-box-shadow:0 2px 10px #898989;box-shadow:0 2px 10px #898989;"></div>



        </div>

      </div>
</div><!--container-->
<script type="text/javascript">

(function() {
window.onload = function(){
var vikey = [{ stylers: [{ gamma: 0.52 },{ saturation: 11 } ] }];
var latlng = new google.maps.LatLng(<?php echo $this->coo_region['lat']; ?> , <?php echo $this->coo_region['lng']; ?>);
var options = {
	zoom: 8,
	center: latlng,
	backgroundColor: '#fff',
	mapTypeId: google.maps.MapTypeId.ROADMAP,
	styles: vikey
};

var map = new google.maps.Map(document.getElementById('maps_canvas'), options);
var json = <?php echo $this->jmaps; ?>;

var Nowmarkers = [];
var shadow = new google.maps.MarkerImage(
    'http://bazoomba/uploaded/marker/shadow.png',
    new google.maps.Size(54,37),
    new google.maps.Point(0,0),
    new google.maps.Point(16,37)
  );
infowindow = new google.maps.InfoWindow({
             content: "loading…"
             });

function Tooltip(nome,markers,image) {
	google.maps.event.addListener(markers, "click", function () {
        var div = '<img src="http://bazoomba/image.php?mode=crop&folder=ads&image='+image+'&width=200&height=150" /> '+name+'';
        infowindow.setContent(div);
        infowindow.open(map, this);
        });
}

for (i=0; i < json.length; i++) {
var lat = new google.maps.LatLng(json[i].latitude, json[i].longitude);
var markerNow = new google.maps.Marker({
	animation: google.maps.Animation.DROP,
	position: lat,
	map: map,
	title: json[i].title,
	shadow: shadow
});
Tooltip(json[i].title, markerNow, json[i].photo);
    Nowmarkers[i] = markerNow;
}
}
})();
</script>


