<!-- title / region -->
<h1>Regione <?php echo $this->region['name']; ?></h1>

<!-- provinces region -->
<?php if ($this->provinces): ?>
	<?php foreach ($this->provinces as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'province', 'item' => $row['id'], 'parent' => $this->region['id']), null, true); ?>"><?php echo $row['name']; ?></a></li>
	</ul>
	<?php endforeach ?>
<?php endif ?>

<!-- list ads -->
<h1>Lista</h1>
<?php if ($this->list): ?>
	<?php foreach ($this->list as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>"><?php echo $row['title']; ?></a></li>
		<li><?php echo $this->truncate($row['description']); ?></li>
		<li><?php echo $row['category']; ?>, <?php echo $row['province']; ?></li>
		<li><?php echo $this->type_ads[$row['type']]; ?>, € <?php echo $row['price']; ?></li>
	</ul>
	<hr>
	<?php endforeach ?>
<?php else: ?>
	<p><?php echo $this->notfound; ?></p>
<?php endif ?>

<!-- region -->
<h1>Italia</h1>
<?php if ($this->other): ?>
	<?php foreach ($this->other as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'region', 'item' => $row['id']), null, true); ?>"><?php echo $row['name']; ?></a></li>
	</ul>
	<?php endforeach ?>
<?php endif ?>