<?php echo $this->headTitle($this->region['name']); ?>

<div class="container">
    <div class="row" style="margin-top: 20px;">

        <div class="span3">

            <div class="row">
                <div class="span2">
                        <div class="btn-group" style="margin-bottom: 10px;">
                        <button class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i> <?php echo $this->region['name']; ?> <span class="caret"></span></button>
                        <ul class="dropdown-menu">
                        <?php foreach ($this->provinces as $row): ?>
                        <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'province', 'item' => $row['id'], 'parent' => $this->region['id']), null, true); ?>/<?php echo $this->seourl($row['name']); ?>"><?php echo $row['name']; ?></a></li>
                        <?php endforeach ?>
                        </ul>
                        <button class="btn" style="margin-left: 5px;"><i class="icon-th"></i></button>
                        </div><!-- /btn-group -->
                </div><!--span2-->
            </div><!--row-->

            <div class="row">
                <div class="span2">
                     <ul class="nav nav-tabs nav-stacked" style="background: #fff;">
                     <li><a href="#"><strong>Annunci Trovati </strong><span class="badge badge-warning"> <?php echo count($this->list); ?></span></a></li>
                     </ul>
                </div><!--span2-->
            </div><!--row-->

            <div class="row">
                <div class="span2">
                     <ul class="nav nav-tabs nav-stacked" style="background: #fff;">
                     <?php foreach ($this->type_user as $key => $value): ?>
                        <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'region', 'item' => $this->region['id'], 'user' => $key), null, true); ?>"><?php echo $value; ?></a></li>
                    <?php endforeach ?>
                    </ul>
                </div><!--span2-->
            </div><!--row-->

            <div class="row">
                <div class="span2">
                     <ul class="nav nav-tabs nav-stacked" style="background: #fff;">
                     <?php foreach ($this->type_ads as $key => $value): ?>
                        <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'region', 'item' => $this->region['id'], 'ads' => $key), null, true); ?>"><?php echo $value; ?></a></li>
                    <?php endforeach ?>
                    </ul>
                </div><!--span2-->
            </div><!--row-->

            <div class="row">
                <div class="span2">
                     <div class="alert alert-success">
                        <strong>Non hai trovato quello che cerhi?</strong>
                        <p>Non demordere, scopri il nostro servizio che ti trova subito ciò che ti serve.
                        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'request', 'action' => 'subscribe'), null, true); ?>">Provalo adesso</a></p>
                        </div>
                </div><!--span2-->
            </div><!--row-->

            <div class="row">
                <div class="span2">
                      <div class="alert alert-success">
                        <strong>Sei un azienda?</strong>
                        <p>Scopri <strong>Brand Page</strong>.<br />
                        <a href="#">Scopri adesso</a></p>
                        </div>
                </div><!--span2-->
            </div><!--row-->

        </div><!--span2-->





        <div class="span9">
            <div class="row">
                <?php if ($this->list): ?>
                <ul class="thumbnails">
                    <?php $cnt = 1; ?>
                    <?php foreach ($this->list as $row): ?>

                        <li class="span3" style="background: #fff;">
                        <div class="thumbnail">
                        <img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=480&height=360" alt="<?php echo $row['title']; ?>" title="<?php echo $row['title']; ?>">
                        <div class="caption" style="min-height: 170px;">
                            <h4><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>"><?php echo $row['title']; ?></a></h4>
                            <p><?php echo $this->truncate($row['description'])->toLength(100); ?></p>
                            <p><a href="#" class="btn btn-warning">€ <?php echo $row['price']; ?></a> <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>" class="btn">Dettaglio</a>
                            <button type="button" class="btn"><i class="icon-info-sign"></i></button></p>
                        </div>
                        </div>
                        </li>
                <?php if($cnt % 3 == 0): ?>
                </ul>
                <ul class="thumbnails">
                <? endif; ?>


                    <?php $cnt++; ?>
                    <?php endforeach ?>
                </ul>
                <?php else: ?>
                <p><?php echo $this->notfound; ?></p>

                <?php endif ?>
            </div><!--row-->

        </div><!--spam10-->





    </div><!--row-->







<!-- list ads -->
<h1>Lista</h1>
<?php if ($this->list): ?>
	<?php foreach ($this->list as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>"><?php echo $row['title']; ?></a></li>
		<li><?php echo $this->truncate($row['description']); ?></li>
		<li><?php echo $row['category']; ?>, <?php echo $row['province']; ?></li>
		<li><?php echo $this->type_ads[$row['type']]; ?>, € <?php echo $row['price']; ?></li>
		<li><?php echo $this->type_user[$row['type_user']]; ?></li>
		<li><img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=100&height=100"></li>
	</ul>
	<hr>
	<?php endforeach ?>
<?php else: ?>
	<p><?php echo $this->notfound; ?></p>
<?php endif ?>

<!-- region -->
<h1>Italia</h1>
<?php if ($this->other): ?>
	<?php foreach ($this->other as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'region', 'item' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['name']); ?>"><?php echo $row['name']; ?></a></li>
	</ul>
	<?php endforeach ?>
<?php endif ?>






</div><!--container-->