<?php
$this->headTitle('Ricerca');
$locale = new Zend_Locale('it_IT');
?>

<div class="container">
    <div class="row" style="margin-top: 20px;">

        <div class="span3">

        <div class="row">
                <div class="span3">
                     <ul class="nav nav-tabs nav-stacked" style="background: #fff;">
                     <li>
                     <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'index'), null, true); ?>">
                     <strong>Annunci Trovati</strong> <span class="badge badge-warning cnt_range"> <?php echo $this->total_list; ?></span>
                     </a>
                     </li>
                     </ul>
                </div><!--span3-->
            </div><!--row-->
            
            <div class="row">
                <div class="span3">
                     <div class="alert alert-success">
                        <strong>Non hai trovato quello che cerchi?</strong>
                        <p>Non demordere, scopri il nostro servizio che ti trova subito ci&ograve; che ti serve.
                        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'request', 'action' => 'subscribe'), null, true); ?>">Provalo adesso</a></p>
                        </div>
                </div><!--span3-->
            </div><!--row-->

        </div><!--span2-->


        <div class="span9">
            <div class="row">
                <div class="span9">
                <?php if ($this->list): ?>
                <ul class="thumbnails">
                    <?php $cnt = 1; ?>
                    <?php foreach ($this->list as $row): ?>

                        <li class="span3 box_ads" id="range_<?php echo sprintf('%d', $row['price']); ?>" style="background: #fff;">
                        <div class="thumbnail">
                        <img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=480&height=360" alt="<?php echo $row['title']; ?>" title="<?php echo $row['title']; ?>">
                        <div class="caption" style="min-height: 170px;">
                            <h4><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>"><?php echo $row['title']; ?></a></h4>
                            <p><?php echo $this->truncate($row['description'])->toLength(100); ?></p>
                            <p><a href="#" class="btn btn-warning">€ <?php echo Zend_Locale_Format::toNumber($row['price'], array('precision' => 2, 'locale' => $locale)); ?></a>
                            <button rel="tooltip" title="Tip Utente <?php echo $this->type_user[$row['type_user']]; ?> - <?php echo $row['category']; ?> - <?php echo $row['province']; ?>" type="button" class="btn"><i class="icon-info-sign"></i></button></p>
                        </div>
                        </div>
                        </li>
                <?php if($cnt % 3 == 0): ?>
                </ul>
                <ul class="thumbnails">
                <? endif; ?>


                    <?php $cnt++; ?>
                    <?php endforeach ?>
                </ul>
                
                <div class="breadcrumb">
                <?php echo $this->paginationControl($this->list, 'Sliding', 'filter/pagination.phtml'); ?>
                </div>
                
                <?php else: ?>

                <div class="row">
                            <div class="span9">
                                <div class="alert alert-error">
                                    <strong><i class="icon-exclamation-sign"></i> <?php echo $this->notfound; ?></strong>
                                </div>
                            </div>
                        </div>
                <?php endif ?>
                
                <div id="not_found_range" style="display: none;" class="row">
                            <div class="span9">
                                <div class="alert alert-error">
                                    <strong><i class="icon-exclamation-sign"></i> <?php echo $this->notfound; ?></strong>
                                </div>
                            </div>
                        </div>

                </div>
            </div><!--row-->

        </div><!--spam10-->
    </div><!--row-->

</div><!--container-->

