<!-- list ads -->
<h1>Circa <?php echo count($this->list); ?> risultati con la parola "<?php echo $this->q; ?>"</h1>
<?php if ($this->list): ?>
	<?php foreach ($this->list as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'id' => $row['id']), null, true); ?>"><?php echo $row['title']; ?></a></li>
		<li><?php echo $row['description']; ?></li>
		<li><?php echo $row['region']; ?>, <?php echo $row['province']; ?></li>
		<li><?php echo $this->type_ads[$row['type']]; ?>, € <?php echo $row['price']; ?></li>
	</ul>
	<hr>
	<?php endforeach ?>
<?php else: ?>
	<p><?php echo $this->notfound; ?></p>
<?php endif ?>