<?php echo $this->headTitle(sprintf('%s | %s | %s', $this->row['title'], $this->category['name'], $this->region['name'])); ?>

<?php if ($this->user['type'] == 2 AND count($this->othersAdsPage) > 0): ?>
<div class="container" style="margin-top: 20px; margin-bottom: -20px;">
    <div class="row">
        <div class="span12">
            <div class="alert alert-box">
                Questo annuncio è gestito da un azienda verificata <strong>( <?php echo $this->user['name_company']; ?> )</strong>. Guarda tutti gli altri annunci <strong><?php echo $this->user['name_company']; ?>.</strong>
                <span class="pull-right"><a href="#"><button class="btn btn-mini btn" type="button"><i class="icon-tags"></i> Altri Annunci (<?php echo count($this->othersAdsPage); ?>)</button></a></span>
            </div>
        </div>
    </div><!--row-->
</div>
<?php endif; ?>


<div class="container" style="background: #fafafa; border-radius: 5px; border: 1px solid #ccc; margin-top: 20px; margin-bottom: 20px;">

    <div class="row">
        <div class="span12" style="background: #efefef; border-bottom: 1px solid #ccc;">

            <div class="pull-left" style="padding: 12px;">
                <strong>#<?php echo $this->row['code']; ?> - <?php echo new Zend_Date($this->row['registered']); ?></strong>
                <a href="#"><button class="btn btn-mini" type="button"><?php echo $this->type_ads[$this->row['type']]; ?></button></a>
                <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'region', 'item' => $this->region['id']), null, true); ?>"><button class="btn btn-mini" type="button"><?php echo $this->region['name']; ?></button></a>
                <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'province', 'item' => $this->province['id'], 'parent' => $this->region['id']), null, true); ?>"><button class="btn btn-mini" type="button"><?php echo $this->province['name']; ?></button></a>
                <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'category', 'item' => $this->category['id']), null, true); ?>"><button class="btn btn-mini" type="button"><?php echo $this->category['name']; ?></button></a>
                <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'subcategory', 'item' => $this->category['id'], 'parent' => $this->sub_category['id']), null, true); ?>"><button class="btn btn-mini" type="button"><?php echo $this->sub_category['name']; ?></button></a>
            </div><!--pull-left-->

            <div class="pull-right" style="padding: 12px;">
              <button class="btn btn-mini btn" type="button"><i class="icon-print"></i>  Stampa Volantino </button>
              <button class="btn btn-mini btn" type="button"><i class="icon-star"></i>  Aggiungi ai Preferiti</button>
              <button class="btn btn-mini btn" type="button"><i class="icon-fire"></i>  Segnala Annuncio </button>
            </div><!--pull-right-->
        </div><!--span12-->
      </div><!--row-->

    <div class="row">
        <div class="span7">
            <div style="padding: 12px;">
            <h2><?php echo $this->row['title']; ?></h2>
            <div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">

                <div id="myCarousel" class="carousel slide">
                <div class="carousel-inner gallery">



                  <!--GALLERY-->
                  <?php if ($this->gallery): ?>
                  <?php foreach ($this->gallery as $img): ?>
                  <div class="item">
                      <div style="min-height: 400px;">
                    <center><img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $img->image; ?>&width=800&height=600"></center>
                      </div>
                    <div class="carousel-caption">
                      <h4><?php echo $this->row['title']; ?></h4>
                    </div>
                  </div>
                  <?php endforeach ?>
                  <?php endif ?>

                </div><!--carousel-inner-->

                <?php if (count($this->gallery) > 1) : ?>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
                <?php endif; ?>

              </div><!--myCarousel-->

              <div class="row">
                  <div class="span6">
                  <p><?php echo nl2br($this->row['description']); ?></p>
                  </div>
              </div>

            </div><!--style-->
            </div><!--style-->
        </div><!--span7-->




        <div class="span3">

                <div class="row">
                    <div class="span3">
                        <div style="padding:12px;">
                            <h2 class="pull-right"> € <?php echo $this->row['price']; ?></h2>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="span3">
                        <div style="padding:12px;">
                            <a href="#myModal" role="button" class="btn btn-large btn-warning pull-right" data-toggle="modal">
                                <i class="icon-envelope icon-white"></i> Contatta Il Venditore
                            </a>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="span3">
                        <div style="padding:12px;">
                            <div style="background: #f6f6f6; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
                                  <div id="maps" style="width: 100%; height: 200px;"></div>
                                  <center><a href="#expMaps" data-toggle="modal"><button style="margin-top: 10px;" class="btn" type="button"><i class="icon-map-marker"></i>  Espandi Mappa</button> </a></center>
                            </div>
                        </div>
                    </div>
                </div>

                <!--ExpMaps-->
                <div id="expMaps" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel">Mappa</h3>
                    </div>
                    <div class="modal-body">
                         <div id="expmaps" style="width: 100%; height: 400px;"></div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-warning" data-dismiss="modal" aria-hidden="true">Chiudi</button>
                    </div>
                </div>

                <div class="row">
                    <div class="span3">
                        <div style="padding:12px;">
                            <div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">


                            <?php if ($this->user['type'] == 1): ?>

                            <img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=avatar&image=<?php echo $this->avatar; ?>&width=480&height=320" alt="<?php echo $this->user['name']; ?>" title="<?php echo $this->user['name']; ?>"/>
                            <center><h4><?php echo $this->user['name']; ?></h4></center>
                            <center><h5><?php if ($this->user['phone_show'] == 1): ?>Tel. <?php echo $this->user['telephone']; ?><?php endif ?></h5></center>

                            <?php else: ?>

                            <center><img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=logo&image=<?php echo $this->logo; ?>&width=480&height=320" alt="<?php echo $this->user['name_company']; ?>" title="<?php echo $this->user['name_company']; ?>"/></center>

                            <center><h4><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'page', 'action' => 'site', 'item' => $this->page['id']), null, true); ?>"><?php echo $this->user['name_company']; ?></a></h4></center>
                            <center><h5>P.Iva <?php echo $this->user['vat']; ?></h5></center>
                            <?php if($this->page['site']): ?> <center><h5><a href="<?php echo $this->page['site']; ?>" target="_blank"><?php echo $this->page['site']; ?></a></h5></center><?php endif; ?>
                            <?php if($this->page['telephone']): ?><center><h5>Tel. Azienda <?php echo $this->page['telephone']; ?></h5></center><?php endif; ?>
                            <center><h5><?php if ($this->user['phone_show'] == 1): ?>Tel. Responsabile <?php echo $this->user['telephone']; ?><?php endif ?></h5></center>

                            <?php endif; ?>

                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal -->
                <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel">Contatta <?php echo $this->user['name']; ?></h3>
                    </div>
                    <div class="modal-body">
                        <?php echo $this->ReplyForm; ?>
                    </div>
                    <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true">Annula</button>
                        <button class="btn btn-warning">Invia Richiesta</button>
                    </div>
                </div>





        </div><!--span3-->






        <div class="span2">

            <div class="row">
                    <div class="span2">
                        <div style="padding:12px;">
                            <h2 class="pull-left">Vicinanze</h2>
                        </div>
                    </div>
            </div>

            <?php if ($this->random_geo): ?>
                <?php foreach ($this->random_geo as $row): ?>
                <div class="row">
                    <div class="span2">
                        <div style="padding:12px;">
                            <div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
                            <img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=480&height=320">
                                <center><h5><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>"><?php echo $row['title']; ?></a> <br /> € <?php echo $row['price']; ?></h5></center>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach ?>

            <?php else: ?>
             <div class="row">
                    <div class="span2">
                        <div style="padding:12px;">
                            <div class="alert alert-success">
                                <p><?php echo $this->notfound; ?></p>
                            </div>
                       </div>
                   </div>
             </div>
            <?php endif ?>

        </div><!--span2-->


    </div><!--row-->
</div><!--container-->
<script type="text/javascript">
var vikey = [{ stylers: [{ gamma: 0.52 },{ saturation: 11 } ] }];
var latlang = new google.maps.LatLng(<?php echo $this->row['latitude']; ?>,<?php echo $this->row['longitude']; ?>);
var mapOptions = {
    center: latlang,
    zoom: 9,
    disableDefaultUI: true,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    styles: vikey
};

var map = new google.maps.Map(document.getElementById("maps"),
mapOptions);
var marker = new google.maps.Marker({ position: latlang,map: map,title: "<?php echo $this->row['title']; ?>" });

/** Exp Maps*/
var expvikey = [{ stylers: [{ gamma: 0.52 },{ saturation: 11 } ] }];
var explatlang = new google.maps.LatLng(<?php echo $this->row['latitude']; ?>,<?php echo $this->row['longitude']; ?>);
var mapOptions = {
    center: explatlang,
    zoom: 9,
    disableDefaultUI: true,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    styles: expvikey
};

var map = new google.maps.Map(document.getElementById("expmaps"),
mapOptions);
var expmarker = new google.maps.Marker({ position: explatlang,map: map,title: "<?php echo $this->row['title']; ?>" });
</script>



