<hr>
<h1><?php echo $this->row['title']; ?></h1>
<ul>
	<li><?php echo $this->row['code']; ?></li>
	<li><?php echo $this->category['name']; ?></li>
	<li><?php echo $this->sub_category['name']; ?></li>
	<li><?php echo $this->region['name']; ?></li>
	<li><?php echo $this->province['name']; ?></li>
	<li><?php echo $this->city['name']; ?></li>
	<li><?php echo $this->type_ads[$this->row['type']]; ?></li>
	<li>€ <?php echo $this->row['price']; ?></li>
</ul>

<ul>
	<li><?php echo $this->user['name']; ?></li>
	<li><?php echo $this->user['telephone']; ?></li>
</ul>

<p><?php echo $this->row['description']; ?></p>

<h1>Photo Gallery</h1>
<?php if ($this->gallery): ?>
<ul>
	<?php foreach ($this->gallery as $img): ?>
	<li><a href="<?php echo $this->serverUrl(); ?>/uploaded/ads/<?php echo $img->image; ?>"><img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $img->image; ?>&width=100&height=100"></a></li>
	<?php endforeach ?>
</ul>
<?php else: ?>
	<p><?php echo $this->notfound; ?></p>
<?php endif ?>

<h1>Rispondi all'inserzionista</h1>
<?php echo $this->successForm; ?>
<?php echo $this->ReplyForm; ?>

<!-- list ads -->
<h1>Nelle vicinanze</h1>
<?php if ($this->random_geo): ?>
	<?php foreach ($this->random_geo as $row): ?>
	<ul>
		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>"><?php echo $row['title']; ?></a></li>
		<li><?php echo $this->truncate($row['description']); ?></li>
		<li><?php echo $row['region']; ?>, <?php echo $row['province']; ?></li>
		<li><?php echo $this->type_ads[$row['type']]; ?>, € <?php echo $row['price']; ?></li>
		<li><?php echo $this->type_user[$row['type_user']]; ?></li>
		<li><img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=100&height=100"></li>
	</ul>
	<hr>
	<?php endforeach ?>
<?php else: ?>
	<p><?php echo $this->notfound; ?></p>
<?php endif ?>

