<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Bazoomba</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><a href="index.html"><i class="icon-home"></i> Home</a></li>
              <li><a href="page.html">Registrati</a></li>
            </ul>

<div class="btn-group pull-left">
  <a class="btn dropdown-toggle active" data-toggle="dropdown" href="#">
    <i class="icon-map-marker"></i> Sicilia
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li><a href="map.html">Abruzzo</a></li>
    <li><a href="#">Basilicata</a></li>
    <li><a href="#">Calabria</a></li>
    <li><a href="#">Campania</a></li>
    <li><a href="#">Emilia-Romagna</a></li>
    <li><a href="#">Friulia Venezia Giulia</a></li>
    <li><a href="#">Lazio</a></li>
    <li><a href="#">Liguria</a></li>
    <li><a href="#"><i class="icon-globe"></i>  Italia</a></li>
  </ul>
</div>

<form class="navbar-search form-search pull-left" style="margin-left: 40px;" action="">
  <div class="input-append">
    <input type="text" class="span3 search-query" placeholder="Iphone 5, Samsung Galasy, BMW, Bilocale ">
    <button type="submit" class="btn btn-warning"><i class="icon-search"></i></button>
  </div>
</form>

            <a class="btn btn-warning pull-right" href="#"><i class="icon-plus icon-white"></i> Inserisci Annuncio Gratis</a>
            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Vincenzo Provenza <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#"> <i class="icon-user"></i> I miei annunci</a> </li>
                  <li><a href="#"> <i class="icon-plus"></i> Crea annuncio</a> </li>
                  <li class="divider"></li>
                  <li class="nav-header"> Profilo</li>
                  <li><a href="#"><i class="icon-pencil"></i> Modifica Dati</a></li>
                  <li><a href="#"><i class="icon-lock"></i> Modifica Password</a></li>
                  <li><a href="#"><i class="icon-picture"></i> Immagine di profilo</a></li>
                  <li><a href="#"><i class="icon-globe"></i> Brand Page</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="background: #fafafa; border-radius: 5px; border: 1px solid #ccc; margin-top: 20px; margin-bottom: 20px; ">

      <div class="row">
        <div class="span12" style="background: #efefef; border-bottom: 1px solid #ccc;">
          <div style="padding: 12px; overflow: hidden;">
            <div class="pull-left">
            <span><strong>Privato, Inserito il 23/10/2012 <a href="#">Sicilia</a> / <a href="#">Catania</a> / <a href="#">Giarre</a></strong></span>
            </div>

            <div class="pull-right">
              <button class="btn btn-mini btn" type="button"><i class="icon-print"></i>  Stampa Volantino </button>
              <button class="btn btn-mini btn" type="button"><i class="icon-star"></i>  Aggiungi ai Preferiti</button>
              <button class="btn btn-mini btn" type="button"><i class="icon-fire"></i>  Segnala Annuncio </button> </div>

        </div>
        </div>
      </div>


<div class="row">


<div class="span7">
  <div style="padding: 12px;">
  <h2>Nome titolo annuncio test</h2>
  <div class="bs-docs-example" style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
              <div id="myCarousel" class="carousel slide">
                <div class="carousel-inner">
                  <div class="item active">
                    <img src="http://placehold.it/800x600" alt="">
                    <div class="carousel-caption">
                      <h4>First Thumbnail label</h4>
                    </div>
                  </div>
                  <div class="item">
                    <img src="http://placehold.it/800x600" alt="">
                    <div class="carousel-caption">
                      <h4>Second Thumbnail label</h4>
                    </div>
                  </div>
                  <div class="item">
                    <img src="http://placehold.it/800x600" alt="">
                    <div class="carousel-caption">
                      <h4>Third Thumbnail label</h4>
                    </div>
                  </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
              </div>

                <div style="width: 100%;">
                  È universalmente riconosciuto che un lettore che osserva il layout di una pagina viene distratto dal contenuto testuale se questo è leggibile. <br />
                  Lo scopo dell’utilizzo del Lorem Ipsum è che offre una normale distribuzione delle lettere (al contrario di quanto avviene se si utilizzano brevi frasi ripetute, ad esempio “testo qui”), apparendo come un normale blocco di testo leggibile.
                  <br /><br />
                  Molti software di impaginazione e di web design utilizzano Lorem Ipsum come testo modello. Molte versioni del testo sono state prodotte negli anni, a volte casualmente, a volte di proposito (ad esempio inserendo passaggi ironici.
                </div>

            </div>
</div>



</div>
<div class="span3">
<div style="padding: 12px;">
  <h2 class="pull-right"> € 3200,00</h2>

<div style="margin-left: 10px; margin-bottom: 17px;">
<a href="#myModal" role="button" class="btn btn-large btn-warning" data-toggle="modal">
  <i class="icon-envelope icon-white"></i> Contatta Il Venditore</a>
</div>


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Contatta Vincenzo Provenza</h3>
  </div>
  <div class="modal-body">
    <p>Form per contatto.</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Annula</button>
    <button class="btn btn-warning">Invia Richiesta</button>
  </div>
</div>



<div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
  <div id="maps" style="width: 100%; height: 200px;"></div>
</div>


<div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px; margin-top: 17px;">
  <img src="http://placehold.it/480x320" alt="">
  <h4 style="margin-left: 27px;">Vincenzo Provenza</h4>
  <h5 style="margin-left: 27px;">Tel: 340 8877665</h5>
</div>


</div>
</div>
<div class="span2">
<div style="padding: 12px;">
  <h4>Nelle Vicinanze</h4>

<div class="row">
  <div class="span2">
    <div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
    <img src="http://placehold.it/200x100" alt="">
    <strong>Nome Annuncio <br /> € 1200,00</strong>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span2">
    <div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
    <img src="http://placehold.it/200x100" alt="">
    <strong>Nome Annuncio <br /> € 1200,00</strong>
    </div>
  </div>
</div>

 <div class="row-fluid">

  <div class="span2">
    <div style="background: #fff; border: 1px solid #ccc; border-radius: 5px; padding: 10px;">
    <img src="http://placehold.it/200x100" alt="">
    <strong>Nome Annuncio <br /> € 1200,00</strong>
    </div>
  </div>

</div>





</div>
</div>


</div>





    </div> <!-- /container -->



<footer style="width: 100%; margin-top: 10px; padding-top: 15px; padding-bottom: 15px; background: url('css/body_bg.png') repeat; border-top: 1px solid #ccc;">
   <div class="container">
        <div class="row">

          <div class="span4">
          <p><small>&copy; Company 2012</small></p>
          </div>

          <div class="span8">
            <span class="pull-right">
            <small>
            <a href="#">Come Funziona</a> |
            <a href="#">Registrati</a> |
            <a href="#">Crea Annuncio</a> |
            <a href="#">Preferiti</a> |
            <a href="#">Tags</a> |
            <a href="#">Contattaci</a>
          </small>
          </span>
          </div>

        </div>
       </div>

      </footer>

      <!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Seleziona Categoria</h3>
  </div>
  <div class="modal-body">

<div class="control-group">
    <div class="controls">
    <select class="span3">
  <option value="1">Elettronica</option>
  <option value="1">Lavoro</option>
</select>
  </div>
</div>



  </div>
  <div class="modal-footer">
    <button class="btn btn-warning">Vai</button>
  </div>
</div>

     


