<?php $this->layout()->setLayout('login'); ?>

<div class="">
	<?php echo $this->render('globals/menu_admin.phtml'); ?>
</div>

<div class="row">
	<div class="twelve columns centered">
		<h2>Annunci</h2>
		<h4 class="subheader">Dettaglio completo</h4>
		<table class="twelve">
			<thead>
				<tr>
					<th colspan="2">Riepilogo</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>ID</td>
					<td><?php echo $this->row['id']; ?></td>
				</tr>
				<tr>
					<td>Codice</td>
					<td><?php echo $this->row['code']; ?></td>
				</tr>
				<tr>
					<td>Titolo annuncio</td>
					<td><?php echo $this->row['title']; ?></td>
				</tr>
				<tr>
					<td>Categoria</td>
					<td><?php echo $this->category['name']; ?> (<?php echo $this->sub_category['name']; ?>)</td>
				</tr>
				<tr>
					<td>Regione</td>
					<td><?php echo $this->region['name']; ?></td>
				</tr>
				<tr>
					<td>Provincia</td>
					<td><?php echo $this->province['name']; ?></td>
				</tr>
				<tr>
					<td>Comune</td>
					<td><?php echo $this->city['name']; ?></td>
				</tr>
				<tr>
					<td>Prezzo</td>
					<td>€ <?php echo $this->row['price']; ?></td>
				</tr>
			</tbody>
		</table>

		<table class="twelve">
			<thead>
				<tr>
					<th colspan="2">Utente</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Pubblica come</td>
					<td><?php echo $this->type_user[$this->user['type']]; ?></td>
				</tr>
				<tr>
					<td>Nome</td>
					<td><?php echo $this->user['name']; ?></td>
				</tr>
				<tr>
					<td>Indirizzo E-mail</td>
					<td><?php echo $this->user['email']; ?></td>
				</tr>
				<tr>
					<td>Telefono</td>
					<td><?php echo $this->user['telephone']; ?></td>
				</tr>
				<tr>
					<td>Tipo di annuncio</td>
					<td><?php echo $this->type_ads[$this->row['type']]; ?></td>
				</tr>
			</tbody>
		</table>

		<table class="twelve">
			<thead>
				<tr>
					<th>Testo</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><?php echo $this->row['description']; ?></td>
				</tr>
				<tr>
					<td><?php echo $this->row['tags']; ?></td>
				</tr>
			</tbody>
		</table>

		<table class="twelve">
			<thead>
				<tr>
					<th colspan="2">Informazioni</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Coordinate GPS da GoogleMaps</td>
					<td>Lat: <?php echo $this->row['latitude']; ?> - Lon: <?php echo $this->row['longitude']; ?></td>
				</tr>
				<tr>
					<td>Stato</td>
					<td><?php echo $this->status[$this->row['status']]; ?></td>
				</tr>
				<tr>
					<td>Termini e condizioni</td>
					<td><?php echo $this->alert[$this->row['terms']]; ?></td>
				</tr>
				<tr>
					<td>Pubblicazione</td>
					<td><?php echo $this->row['registered']; ?></td>
				</tr>
				<tr>
					<td>Revisione</td>
					<td><?php echo $this->row['modified']; ?></td>
				</tr>
				<tr>
					<td>Browser Web</td>
					<td><?php echo $this->row['computer']; ?></td>
				</tr>
				<tr>
					<td>Indirizzo IP</td>
					<td><?php echo $this->row['ip_address']; ?></td>
				</tr>
			</tbody>
		</table>

	</div>

</div>

<?php echo $this->render('globals/copyright_admin.phtml'); ?>