<div class="container" style="margin-top: 20px; margin-bottom: -20px;">
<h1>2 STEP</h1>
<p><b><?php echo $this->identity->name; ?></b> , aggiungi foto...</p>
<?php echo $this->addMedia; ?>

<?php if(count($this->gallery) > 0): ?>
<ul>
    <?php foreach ($this->gallery as $row): ?>
    <li>
     	<img src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row->image; ?>&width=100&height=100">
        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'gallery', 'action' => 'deletemedia', 'id' => $row->id, 'ads' => $this->id_ads), null, true); ?>">Elimina X</a>
    </li>
    <?php endforeach ?>
</ul>
<?php endif; ?>
<br /><br />
<?php if(count($this->gallery) > 0): ?>
<a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'public', 'id' => $this->id_ads), null, true); ?>" class="btn btn-primary">Pubblica il tuo annuncio ora</a>
<?php endif; ?>
<br />
</div>
