<?php echo $this->headTitle('I miei annunci - '.$this->identity->name.''); ?>
<div class="container" style="background-color: #f0f0f0; border-radius: 15px; margin-top: 20px;">

    <?php echo $this->render('globals/menu_user.phtml'); ?>

    <div class="row">
        <div class="span12">
            <div style="padding: 12px;">

                <div style="background-color: #fff; padding: 10px; border: 1px solid #ccc; border-radius: 5px; margin-top: -25px;">

                    <?php if ($this->myshop): ?>
                    <div class="btn-group">
                    <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">Annunci (<?php echo count($this->myshop); ?>) <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#">Ordina Per Attivi</a></li>
                        <li><a href="#">Ordina Per Sospesi</a></li>
                        <li><a href="#">Ordina Per Data</a></li>
                    </ul>
                    </div><!-- /btn-group -->



                     <?php foreach ($this->myshop as $row): ?>
                     <div class="row" style="margin-top: 10px; margin-bottom: 10px;">

                         <div class="span3">
                             <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>">
                                 <img class="photoAT" src="<?php echo $this->serverUrl(); ?>/image.php?mode=crop&folder=ads&image=<?php echo $row['photo']; ?>&width=480&height=360">
                             </a>
                         </div>

                         <div class="span8">
                             <div style="padding: 12px;">

                                <h4><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>"><?php echo $row['title']; ?></a></h4>
                                <p><?php echo $this->truncate($row['description']); ?></p>
                                <h4>€ <?php echo $row['price']; ?> - Inserito il <?php echo new Zend_Date($row['registered']); ?></h4>

                                <?php if($row['step'] == 1 AND $row['status'] == 0): ?>
                                <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'media', 'id' => $row['id']), null, true); ?>" class="btn btn-warning">Aggiungi Immagini</a>
                                <?php endif; ?>

                                <?php if($row['step'] == 2 AND $row['status'] == 0): ?>
                                <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'public', 'id' => $row['id']), null, true); ?>" class="btn btn-warning">Pubblica Ora</a>
                                <?php endif; ?>

                                <?php if($row['step'] == 3 AND $row['status'] == 0): ?>
                                <a href="#" class="btn btn-info">Annuncio In Attesa Di Approvazione</a>
                                <?php endif; ?>

                                <?php if($row['step'] == 3 AND $row['status'] == 1): ?>
                                <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'ads', 'show' => $row['id']), null, true); ?>/<?php echo $this->seourl($row['title']); ?>" class="btn btn-success"><i class="icon-ok icon-white"></i> Attivo</a>

                                <div class="btn-group">
                                <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><i class="icon-remove"></i> Elimina Annuncio <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'delete', 'ads' => $row['id'], 'item' => 1), null, true); ?>">Elimina perchè non più disponibile.</a></li>
                                    <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'delete', 'ads' => $row['id'], 'item' => 2), null, true); ?>">Elimina perchè venduto.</a></li>
                                    <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'delete', 'ads' => $row['id'], 'item' => 3), null, true); ?>">Elimina per motivi personali/altro.</a></li>
                                    <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'delete', 'ads' => $row['id'], 'item' => 4), null, true); ?>">Elimina perchè non mi piace Bazoomba.</a></li>
                                </ul>
                                </div>
                                <?php endif; ?>


                            </div><!--padding-->
                         </div><!--span8-->

                     </div><!-- row-->
                     <?php endforeach ?>


                      <?php else: ?>

                        <div class="row">
                            <div class="span11">
                                <div class="alert alert-error" style="margin-left: auto; margin-right: auto;">
                                    <strong>Non hai inserito nessun annuncio attualmente. Pubblica adesso il tuo primo annuncio.</strong>
                                </div>
                            </div>
                        </div>

                    <?php endif; ?>

                </div><!--style-->
            </div><!--padding-->
        </div><!--12-->
    </div><!--row-->

</div><!--container-->


