<?php $this->layout()->setLayout('login'); ?>

<div class="">
	<?php echo $this->render('globals/menu_admin.phtml'); ?>
</div>

<div class="row">
	<div class="twelve columns centered">
		<h2>Annunci</h2>
		<h4 class="subheader">Ricerca avanzata</h4>


		<div href="#" class="button split dropdown">
			<a href="javascript:void(0)">Tipo di annuncio</a>
			<span></span>
			<ul>
				<?php foreach ($this->type_ads as $key => $value): ?>
				<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'type', 'q' => $key), null, true); ?>"><?php echo $value; ?></a></li>
				<?php endforeach ?>
			</ul>
		</div>

		<div href="#" class="button split dropdown">
			<a href="javascript:void(0)">Stato</a>
			<span></span>
			<ul>
				<?php foreach ($this->status as $key => $value): ?>
				<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'status', 'q' => $key), null, true); ?>"><?php echo $value; ?></a></li>
				<?php endforeach ?>
			</ul>
		</div>

		<div href="#" class="button split dropdown">
			<a href="javascript:void(0)">Categoria</a>
			<span></span>
			<ul>
				<?php foreach ($this->category as $row): ?>
				<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'category', 'q' => $row['id']), null, true); ?>"><?php echo $row['name']; ?></a></li>
				<?php endforeach ?>
			</ul>
		</div>

		<div href="#" class="button split dropdown">
			<a href="javascript:void(0)">Italia</a>
			<span></span>
			<ul>
				<?php foreach ($this->region as $row): ?>
				<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'region', 'q' => $row['id']), null, true); ?>"><?php echo $row['name']; ?></a></li>
				<?php endforeach ?>
			</ul>
		</div>





</div>

</div>

<?php echo $this->render('globals/copyright_admin.phtml'); ?>