<?php $this->layout()->setLayout('login'); ?>

<div class="">
	<?php echo $this->render('globals/menu_admin.phtml'); ?>
</div>

<div class="row">
	<div class="twelve columns centered">
		<h2>Annunci</h2>
		<h4 class="subheader">Ricerca avanzata</h4>
	</div>
</div>

<div class="row">
	
	<div class="twelve columns centered">

		<ul class="accordion">
		  
		  <li class="active">
		    <div class="title">
		      <h5>Tipo di annuncio</h5>
		    </div>
		    <div class="content">
		      <ul class="disc">
		      	<?php foreach ($this->type_ads as $key => $value): ?>
		      		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'type', 'q' => $key), null, true); ?>"><?php echo $value; ?></a></li>
		      	<?php endforeach ?>
		      </ul>
		    </div>
		  </li>

		  <li>
		    <div class="title">
		      <h5>Stato</h5>
		    </div>
		    <div class="content">
		    	<ul class="disc">
		    		<?php foreach ($this->status as $key => $value): ?>
		    		<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'status', 'q' => $key), null, true); ?>"><?php echo $value; ?></a></li>
		    		<?php endforeach ?>
		    	</ul>
		    </div>
		</li>

		  <li>
		    <div class="title">
		      <h5>Categoria</h5>
		    </div>
		    <div class="content">
		      <ul class="disc">
			<?php foreach ($this->category as $row): ?>
				<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'category', 'q' => $row['id']), null, true); ?>"><?php echo $row['name']; ?></a></li>
			<?php endforeach ?>
		</ul>
		    </div>
		  </li>

		    <li>
		      <div class="title">
		        <h5>Regione</h5>
		      </div>
		      <div class="content">
		        <ul class="disc">
			<?php foreach ($this->region as $row): ?>
				<li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'list', 'search' => 'region', 'q' => $row['id']), null, true); ?>"><?php echo $row['name']; ?></a></li>
			<?php endforeach ?>
		</ul>
		      </div>
		    </li>

		</ul>

	</div>

</div>

<?php echo $this->render('globals/copyright_admin.phtml'); ?>