<?php $this->layout()->setLayout('login'); ?>

<div class="row">
	<div class="six columns centered">
		<h2>Bazoomba Administrator</h2>
		<p>Administrator Reserved: please Login to manage site.</p>
		<hr />

		<?php if ($this->loginError): ?>
		<div class="alert-box alert"><?php echo $this->loginError; ?><a href="" class="close">&times;</a></div>
	<?php endif ?>

	<?php echo $this->loginForm; ?>
</div>
</div>