<!doctype html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Bazoomba</title>
	<link href="<?php echo $this->serverUrl(); ?>/site/css/bootstrap.css" rel="stylesheet">
	<link href="<?php echo $this->serverUrl(); ?>/site/css/bootstrap-responsive.css" rel="stylesheet">
</head>

<body>

	<div class="container">

		<?php echo $this->layout()->content; ?>
		<hr>

		<p>Grazie di utilizzare Bazoomba!</p>
		<p>Cordiali saluti<br>- Il team di Bazoomba.it</p>
		<p>&nbsp;</p>
		<p><i>Le informazioni in questa e-mail sono confidenziali e riservate esclusivamente al destinatario del messaggio.</i></p>
		
	</div>
</body>
</html>