<?php

/** set head meta */
$this->headTitle($this->setting['title']);
$this->headTitle()->setSeparator(' | ');
$this->headMeta()->appendName('keywords', '');
$this->headMeta()->appendName('description', '');

/** @var $select new obj Select */
$select = new Application_Model_OptionSelect();

/** @var $region_select list of region */
$region_select = $select->RegionByAds();

?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(); ?>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $this->serverUrl(); ?>/site/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $this->serverUrl(); ?>/site/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="<?php echo $this->serverUrl(); ?>/site/css/style.css" rel="stylesheet">
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    
    <script src="<?php echo $this->serverUrl(); ?>/site/js/jquery.validate.js"></script>
    <script src="<?php echo $this->serverUrl(); ?>/site/js/validate.js"></script>
    <script src="<?php echo $this->serverUrl(); ?>/site/js/bootstrap.js"></script>
    <script src="<?php echo $this->serverUrl(); ?>/site/js/bootstrap-tooltip.js"></script>
    <script src="<?php echo $this->serverUrl(); ?>/site/js/app.js"></script>
    <script src="<?php echo $this->serverUrl(); ?>/site/js/jquery.ui.map.js"></script>
    <script src="<?php echo $this->serverUrl(); ?>/site/js/getCurrentPosition.js"></script>
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <!--Logo-->
                    <a class="brand" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>">Bazoomba</a>

                    <div class="nav-collapse collapse navbar-responsive-collapse">
                        <ul class="nav">
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'index', 'action' => 'index'), null, true); ?>"><i class="icon-home"></i> Home</a></li>
                            <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'new'), null, true); ?>">Registrati</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-map-marker"></i><span id="name_region">Italia</span><b class="caret"></b></a>
                                <ul class="dropdown-menu">

                                   <?php foreach ($region_select as $key => $value): ?>
                                        <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'filter', 'action' => 'region', 'item' => $key), null, true); ?>"><?php echo $value; ?></a></li>
                                   <?php endforeach; ?>
                           </ul>
                       </li>
                   </ul>

                   <!--Search Form-->
                   <form class="navbar-search form-search pull-left" action="">
                    <div class="input-append">
                        <input type="text" class="span3 search-query" placeholder="Iphone 5, Samsung Galasy, BMW, Bilocale">
                        <button type="submit" class="btn btn-warning"><i class="icon-search"></i></button>
                    </div>
                </form>

                <a class="btn btn-warning pull-right" href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'new'), null, true); ?>"><i class="icon-plus icon-white"></i> Inserisci Annuncio Gratis</a>
                <ul class="nav pull-right">
                    <?php if ($this->identity): ?>
                    <li class="dropdown">
                       <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->identity->name; ?><b class="caret"></b></a>
                       <ul class="dropdown-menu">
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'my'), null, true); ?>"> <i class="icon-user"></i> I miei annunci</a> </li>
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'new'), null, true); ?>"> <i class="icon-plus"></i> Crea annuncio</a> </li>
                           <li class="divider"></li>
                           <li class="nav-header"> Profilo</li>
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'index'), null, true); ?>"><i class="icon-home"></i> Dashboard</a></li>
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'edit'), null, true); ?>"><i class="icon-pencil"></i> Modifica Dati</a></li>
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'editpassword'), null, true); ?>"><i class="icon-lock"></i> Modifica Password</a></li>
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'avatar'), null, true); ?>"><i class="icon-picture"></i> Immagine di profilo</a></li>
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'account', 'action' => 'favorites'), null, true); ?>"><i class="icon-star"></i> Preferiti</a></li>
                           <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), null, true); ?>"><i class="icon-off"></i> Logout</a></li>
                       </ul>
                   </li>
               <? else: ?>
               <li><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'index'), null, true); ?>"><i class="icon-lock"></i> Esegui Login</a></li>
           <?php endif; ?>
       </ul>
   </div><!--/.nav-collapse -->
</div><!--/.container -->
</div><!--/.navbar-inner -->
</div><!--/.navbar-->

<div class="container" style="padding: 25px;"></div>

<?php echo $this->layout()->content; ?>

</body>
</html>