<p>Gentile Amministratore,</p>
<p>è stato inserito un nuovo annuncio su Bazoomba.it</p>
<p>Breve Riepilogo:</p>
<ul>
	<li>Titolo: <?php echo stripslashes($this->params['title']); ?></li>
	<li>Testo: <?php echo $this->params['description']; ?></li>
</ul>
<hr>
<p><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'shop', 'action' => 'detail', 'id' => $this->params['id']), null, true); ?>">Accedi al software per verificare & confermare l'annuncio.</a></p>