<p>Gentile Amministratore,</p>
<p>è stato inserito un nuovo annuncio su Bazoomba.it</p>
<p>Breve Riepilogo:</p>
<ul>
	<li>Titolo: <?php echo stripslashes($this->params['title']); ?></li>
	<li>Testo: <?php echo stripslashes(substr($this->params['description'],0,200)); ?></li>
</ul>
<hr>
<p><a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'login', 'action' => 'index')); ?>">Accedi al software per verificare & confermare l'annuncio.</a></p>