<?php $this->layout()->setLayout('login'); ?>

<div class="">
	<?php echo $this->render('globals/menu_admin.phtml'); ?>
</div>

<div class="row">
	<div class="seven columns centered">
		<h2>Parametri di Funzionamento</h2>
		<h4 class="subheader">Configurazione</h4>

		<?php if ($this->successForm): ?>
			<div class="alert-box success"><?php echo $this->successForm; ?><a href="" class="close">&times;</a></div>
		<?php endif ?>

		<?php echo $this->settingForm; ?>
	</div>

</div>

<?php echo $this->render('globals/copyright_admin.phtml'); ?>