<?php echo $this->headTitle('Esegui il login - Bazoomba'); ?>

<div class="container" style="padding: 20px;">



            <?php if ($this->loginError): ?>
            <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Errore!</strong> <?php echo $this->loginError; ?>
            </div>
            <?php endif ?>

    <h2>Esegui il Login</h2>
            <?php echo $this->loginForm; ?>
        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'lostpassword')); ?>">Password Smarrita</a>
        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'new')); ?>">Registrati</a>

</div>
