
<div class="container" style="padding: 20px;">

    <div class="row">
        <div class="span8">
            <div style="background-color: #fff; border: 1px solid #f2f2f2; border-radius: 5px; padding: 10px;">

            <?php if ($this->loginError): ?>
            <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Error!</strong> <?php echo $this->loginError; ?>
            </div>
            <?php endif ?>

            <?php echo $this->loginForm; ?>
        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'lostpassword')); ?>">Password Smarrita</a>
        <a href="<?php echo $this->serverUrl(); ?><?php echo $this->url(array('controller' => 'user', 'action' => 'new')); ?>">Registrati</a>
        </div>
        </div>

        <div class="span4">
            <h2>Login</h2>
        </div>


    </div>
</div>
